import { Box, Grid, Typography } from '@mui/material'
import React from 'react'
import chair from '../assets/chair.jpg'

function Home() {
    return (
        <div style={{ position: 'relative' }} >
            <Box sx={{ width: '100%' }}>
                <Box sx={{ width: '100%', height: '50vh', background: '#005B41', position: 'relative' }}>
                    <Grid container spacing={2}>
                        <Grid item md={8} xs={12} sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', width: '100%', height: { md: '50vh', xs: '20vh' } }}>
                            <Typography sx={{ fontSize: { md: '48px', xs: '20px', }, fontFamily: 'Cinzel, serif', color: 'white', }}>Unleash Your</Typography>
                            <Typography sx={{ fontSize: { md: '48px', xs: '20px', }, fontFamily: 'Cinzel, serif', color: 'white', }} >Home's Potentials</Typography>
                            <Typography sx={{ fontSize: { md: '48px', xs: '20px', }, fontFamily: 'Cinzel, serif', color: 'white', }}>with Our Furniture</Typography>
                            <button className='btnHome'> Shop all</button>
                        </Grid>
                        <Grid item md={4} xs={12} sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', width: '100%', height: { md: '50vh', xs: '25vh' } }}>
                            <img
                                src={chair}
                                width='60%'
                                height='auto'
                                style={{ borderRadius: '50%' }}
                            />
                        </Grid>
                    </Grid>
                </Box>
                <Box sx={{
                    width: '100%', height: '36vh', paddingY: '20px'
                }}>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '25px', xs: '20px', }, fontFamily: 'Cinzel, serif', color: 'black', }}>Best Services For You</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                    <Typography sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: { md: '14px', xs: '20px', }, fontFamily: 'Raleway, sans-serif', color: 'black', fontWeight: 'bold' }}>Enjoy our best service for your shopping satisfaction</Typography>
                </Box>
            </Box>
        </div >
    )
}

export default Home